# Num py
https://numpy.org/doc/stable/user/absolute_beginners.html



## O array no numpy


In [3]:
#importando o numpy
import numpy as np

In [69]:
a = np.arange(15).reshape(3,5)


In [70]:
display(a)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
#veriicando a dimensão desse array
a.ndim

2

In [7]:
#Verificando o tipo dos dados
a.shape

(3, 5)

In [8]:
a.dtype

dtype('int32')

In [10]:
#adicionando array
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [11]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [13]:
#classificar rapidamente os números em ordem crescente com:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
#criar um array com intervalo de valores
ab = np.arange(10)

In [15]:
ab

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#passar o primeiro valor e o ultimo valor
ab = np.arange(2,10)
ab

array([2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
#Com intervalor --> o segundo termo é o excludente e o terceiro argumento vai ser o passo
a = np.arange(5,101, 5)

In [ ]:
# Com intervalo decrescente - o segundo termo é o excludente, terceiro vai ser o passo (decrescente so passar o termo negativa)
np.arange(100,4, -5)

## numpy.linspace 
numpy.linspace ( início , parada , num = 50 , ponto final = Verdadeiro , retstep = Falso , dtype = Nenhum , eixo = 0 , * , dispositivo = Nenhum )

In [40]:
# quero buscar a faixa de idade de 16 anos a 80 dividindo em 21 grupos
a = np.linspace(16, 80, num=5)
a

array([16., 32., 48., 64., 80.])

# ------------------------------------------
## Buscando elementos no array

In [46]:
b[0],b[1], b[2]

(array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]))

In [48]:
#buscar o lemento 3 na primeira linha
b[0] [3]

3

In [51]:
b[2][2]

10

In [52]:
#Buscando os elementos de indice 1 a 3 (excluindo o 3º indice) n primeira linha
b[0][1:3]

array([1, 2])

In [55]:
#buscar os valores > 5
b[b>5]

array([ 6,  7,  8,  9, 10, 11])

In [57]:
# buscando valores maiores que 5 e(&) ou (|) menores que 12
b[(b>3) & (b<=10)]

array([ 4,  5,  6,  7,  8,  9, 10])

### Operações básicas no array 
Operadores aritméticos em arrays aplicam -se elemento a elemento . Um novo array é criado e preenchido com o resultado.

In [68]:
display(ab)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
#soma todos os valores do array
ab.sum()

44

In [71]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [99]:
#soma somente os valores da linha
b.sum(axis=0)

array([12, 15, 18, 21])

In [103]:
#soma somente os valores da linha indexada
b[0].sum(axis=0), b[1].sum(axis=0), b[2].sum(axis=0)

(6, 22, 38)

In [98]:
#soma somente os valores da linhas
b.sum(axis=1)

array([ 6, 22, 38])

In [94]:
#Multiplicando ou somando 2 a todos os valores do array
b*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [95]:
#Verificando o menor valor desse array
b.min()

0

In [96]:
#Verificando o maior valor desse array
b.max()

11

In [86]:
cd = np.arange(0,22,5)

In [87]:
cd

array([ 0,  5, 10, 15, 20])

In [85]:
cd.sum()

4950